drop table if exists users, orders_items, orders, items;

create table users
(
    id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login            varchar(100),
    password         varchar(100),
    role             varchar(50),
    number_phone     varchar(50) UNIQUE,
    address          varchar(150),
    can_create_order boolean,
    dtype            varchar(100)
);

create table orders
(
    id_order      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_customer   int REFERENCES users (id) on DELETE CASCADE,
    id_specialist int REFERENCES users (id) on DELETE SET NULL,
    status_order  varchar(100),
    order_price int
);

create table items
(
    id_item    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name  varchar(100) NOT NULL UNIQUE,
    item_price real         NOT NULL
);

create table orders_items
(
    id_order int REFERENCES orders (id_order),
    id_item  int REFERENCES items (id_item) on DELETE CASCADE
);

-- login Artem, pass 777 - Admin
-- login Vasek pass 888 - Spec
-- login Vitalik pass 111 - Customer
-- login Petya pass 000 - Customer
-- login Gena pass 999 - Spec
insert into users(login, password, role, dtype)
values ('Artem', '$2a$10$iU6eKBLGoyqPvYHEHczMRexDhmHzoCA9E1M0IMpHYR2diozsz5ZN2', 'ADMIN', 'Employee'),
       ('Vasek', '$2a$10$uumlsACCWeEwQLIyELEWC.5WHtkN7HdLQgTHXAFsF1Do9s/UvAIbq', 'SPECIALIST', 'Employee'),
       ('Vitalik', '$2a$10$85jstNk0dFxCLcsg/b5CuuWtZAxDRXLcestYDeHqjSQbgfpPX0bVe', 'CUSTOMER', 'Customer'),
       ('Petya', '$2a$10$AXZzIxaXkz0574ZstT7XRufR9reJF9PIYMODTxSzFTpH2t7CKjSrm', 'CUSTOMER', 'Customer'),
       ('Gena', '$2a$10$3F0lCau1mQfu4Cpm0y3ynuix25ag9uBDskOAiLIrSB8RSU5TATfwi', 'SPECIALIST', 'Employee');


insert into items(item_name, item_price)
values ('Chair', 500),
       ('Sofa', 1000),
       ('Bed', 2000);

insert into orders(id_customer, id_specialist, status_order)
values (3, 2, 'IN_PROCESS'),
       (3, 5, 'READY'),
       (4, 2, 'READY'),
       (4, 2, 'IN_PROCESS');

insert into orders_items(id_order, id_item)
values (1, 1),
       (1, 2),
       (1, 3),
       (2, 2),
       (3, 2),
       (3, 3),
       (4, 1);
